### ISSUE TITLE
Add an .env file and extract the API_TOKEN from the .env file

### ISSUE THREAD

**Issue by jajodiaraghav** [jajodiaraghav/rTunes#10]

**Comment by marvin08** [comment]
@jajodiaraghav I want to work on this. Please tell me how to proceed.

**Comment by hiteshpr** [comment]
@jajodiaraghav solved the issue and created a pull request. Please review.

**Comment by jajodiaraghav** [comment]
@hiteshpr Please claim an issue before creating a Pull request. This is not the right way. Your PR might get rejected if you create a PR for an issue claimed by someone else.

**Comment by hiteshpr** [comment]
@jajodiaraghav ok. I didn't know the procedure. I will keep this in mind.
