### ISSUE TITLE
Create a Scroll Back to Top Button

### ISSUE THREAD

**Issue by aditodkar** [jajodiaraghav/rTunes#21]
![screenshot_1](https://user-images.githubusercontent.com/16613832/33805200-cc0e4a3e-ddda-11e7-8068-9f35f748990d.jpg)

**Comment by aditodkar** [comment]
@jajodiaraghav I will work on this issue :)

**Comment by jajodiaraghav** [comment]
Open for claiming

**Comment by hiteshpr** [comment]
I can work on this!

**Comment by hiteshpr** [comment]
Is this button required on all pages?

**Comment by jajodiaraghav** [comment]
This should only be available on those pages where there is a scrollbar with page size at least twice the window size. I wonder if there is any such page in our app.
