### ISSUE TITLE
Replace broken images with a placeholder image

### ISSUE THREAD

**Issue by jajodiaraghav** [jajodiaraghav/rTunes#27]
Get Image from https://placeholder.com/

This will fix:
![capture](https://user-images.githubusercontent.com/18749480/33880207-eeed839e-df56-11e7-8f68-5b24e30451ec.PNG)

**Comment by bruce-wayne99** [comment]
I would like to work on this issue.

**Comment by jajodiaraghav** [comment]
Please don't forget to post a screenshot in your PR when done
