### ISSUE TITLE
Dead links in the list of Albums

### ISSUE THREAD

**Issue by agentcap** [jajodiaraghav/rTunes#29]
The =mbid= returned by the last.fm api is some times null and so the links on the artist page of the albums  are not valid.

**Comment by jajodiaraghav** [comment]
We have to filter such links to not show them in the UI

**Comment by agentcap** [comment]
I would like to work on this.

**Comment by hiteshpr** [comment]
Anyone working on this?

**Comment by jajodiaraghav** [comment]
@agentcap Are you working on it?

**Comment by agentcap** [comment]
@jajodiaraghav I will get it done by tonight and should I filter the results to show only valid links or change the reference to the **#** for the invalid one's?

**Comment by jajodiaraghav** [comment]
@agentcap No issues. Take your time :)

> Should I filter the results to show only valid links or change the reference to the # for the invalid one's?

Show only valid links. We do not want data with invalid links to come in UI

**Comment by hiteshpr** [comment]
Hey, The bug is still there.
See this - 
![screenshot from 2017-12-31 00 55 18](https://user-images.githubusercontent.com/19280178/34456757-77fd07d2-edc5-11e7-96be-328c96ffc8bf.png)

**Comment by agentcap** [comment]
> The =mbid= returned by the last.fm api is some times null and so the links on the artist page of the albums are not valid.

@hiteshpr  This fixes the dead links on the artist page only. I will update this for home page too. Thanks for pointing this out.
