### ISSUE TITLE
Display user ratings on Artists, bands and albums

### ISSUE THREAD

**Issue by jajodiaraghav** [jajodiaraghav/rTunes#3]

**Comment by bruce-wayne99** [comment]
I want to work on this issue but i don't see any api that gives us the ratings on artists etc.

**Comment by jajodiaraghav** [comment]
I am sorry, I don't think we can display user ratings as the API does not provide it.
Although, we can show "PlayCount" and "Listeners" (If not already showing)

Maybe, We can manually show rating conditionally. If the Playcount is > say 10M, we give it 5 stars. and if between 1M to 10M, then 4. Please comment if you have a better approach.

**Comment by bruce-wayne99** [comment]
Ok that's better. I would like to work on this issue.
