### ISSUE TITLE
Create pages for Artists, Albums and tracks with dedicated search

### ISSUE THREAD

**Issue by jajodiaraghav** [jajodiaraghav/rTunes#4]

**Comment by aditodkar** [comment]
I am familiar with Angular2, typescript. Can I work on this issue ?

**Comment by jajodiaraghav** [comment]
Sure, Go ahead @aditodkar 
I haven't yet given much thought to how the pages would look. Can you please run the app locally and explain how you think we could implement this best?

I personally think a single search ribbon with radio/checkbox allowing user to select what he wants to search would be good. What do you think?

**Comment by jajodiaraghav** [comment]
Open for claiming

**Comment by bruce-wayne99** [comment]
i would like to work on this issue

**Comment by bruce-wayne99** [comment]
@jajodiaraghav 
I would like to implement it as you said -
that is a single search bar with radio buttons allowing user to select either album, artist, tracks for searching.
Is it ok?

**Comment by jajodiaraghav** [comment]
Yes @bruce-wayne99
