### ISSUE TITLE
Allow search by tags and genre

### ISSUE THREAD

**Issue by jajodiaraghav** [jajodiaraghav/rTunes#5]

**Comment by bruce-wayne99** [comment]
I want to work on this issue

**Comment by jajodiaraghav** [comment]
Hi @bruce-wayne99 
We already have a PR for this(Implemented Tags). You can work on genres part.
Also there are several other issues that you can claim

**Comment by bruce-wayne99** [comment]
what do you mean by genre exactly in here?

**Comment by bruce-wayne99** [comment]
Yes i would like to work on it!

**Comment by jajodiaraghav** [comment]
I think a dropdown listing the country names would do. Maybe, we can put all the country name and code in a separate file(json) and loop through the contents.
Feel free to mention if you have another approach.

Thanks :)

**Comment by bruce-wayne99** [comment]
I thought of implementing a component 'country' and provide a hyperlink in the navbar which takes you to the page /country where you will having a search engine and you can search by country for artists over there.

**Comment by jajodiaraghav** [comment]
Okay. Let's do it that way :)

**Comment by jajodiaraghav** [comment]
Opened #12
