### ISSUE TITLE
Add link to youtube videos for the particular album/track

### ISSUE THREAD

**Issue by jajodiaraghav** [jajodiaraghav/rTunes#7]

**Comment by agentcap** [comment]
I would like to work on this.

**Comment by jajodiaraghav** [comment]
Sure, Go ahead!

**Comment by agentcap** [comment]
I couldn't find the data for the link to the youtube videos in the api. 
But the play button in the "tracks" page redirects us to last.fm site where there is video from youtube. So I was thinking of scrapping the site and get the link. 
Is there any better approach??

**Comment by jajodiaraghav** [comment]
I was thinking of directly sending the user to Youtube with the track name in the search:
https://www.youtube.com/results?search_query=shape+of+you
